spring:
  application:
    name: shardingJdbcDemo
  #shardingsphere相关配置
  shardingsphere:
    datasource:
      names: db0,db1   #库名，只是名字
      db0: #数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT
        username: root
        password: tacbin@123

      db1: #数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/test1?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT
        username: root
        password: tacbin@123

    sharding: #指定表的分片规则
      tables: # 看到table "s" ，就知道可配置多个
        t_exam: # 指定表名，此名必须和model中 @TableName(value = "t_exam") 一致
          actual-data-nodes: db${0..1}.t_exam #创建了两个表，下标0和1，所以此处配置你懂的
          database-strategy:
            standard:
              sharding-column: id
              precise-algorithm-class-name: club.tacbin.sharding.config.ShardingRuleStrategy
#          table-strategy:
#            standard: # 指定表的分片策略
#              sharding-column: id #参与分片运算的列名
#              precise-algorithm-class-name: club.tacbin.sharding.config.ShardingRuleStrategy #分片算法
          key-generator: # 指定表的主键生成策略
            type: SNOWFLAKE  #SNOWFLAKE
            column: id  #指定主键
    props:
      sql:
        show: true #输出日志

